- name: Kebeadm init
  command: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr={{ pod_cidr }}

- name: print init command
  command: kubeadm token create --print-join-command
  register: kubernetes_join_command

- name: create token 
  template:
    src: templates/token.j2
    dest: /home/{{ user }}/token

- name: fetch token
  fetch:
    src: /home/{{ user }}/token
    dest: /home/{{ user_on_host.stdout }}/token.sh
    flat: yes

