# - name: Pod Network setup
#   raw: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Tiger calio 4
  raw: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

- name: Calico
  raw: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml